<?php

require_once dirname(__FILE__) . '/includes/base_themes.inc';
require_once dirname(__FILE__) . '/includes/menus.inc';
require_once dirname(__FILE__) . '/includes/forms.inc';

/**
 * Load form alter hooks from the /form directory.
 */
$pattern = '.form.inc';
$files = file_scan_directory(dirname(__FILE__) . '/form', "/.form.inc/");
foreach ($files as $filepath => $file) {
  require_once $filepath;
}
