<?php
/**
 * @file
 * wds_2col_rightsidebar.inc
 */

$plugin = array(
  'title' => t('WDS: Right-Sidebar 2 column'),
  'category' => t('WDS: 2'),
  'icon' => 'wds_2col_rightsidebar.png',
  'theme' => 'wds_2col_rightsidebar',
  'admin css' => '../wds_admin_panels.css',
  'regions' => array(
    'top' => t('Top'),
    'left' => t('Left'),
    'right' => t('Right'),
    'bottom' => t('Bottom'),
  ),
);


