<?php

/**
 * @file
 * Definition of constants for USWDS theme.
 */

define('USWDS_MENU_NONE', 'none');
define('USWDS_MENU_REGION_PRIMARY', 'uswds_menu_primary');
define('USWDS_MENU_REGION_SECONDARY', 'uswds_menu_secondary');
define('USWDS_MENU_REGION_SIDE', 'uswds_menu_side');
define('USWDS_MENU_REGION_FOOTER', 'uswds_menu_footer');
define('USWDS_FIELDSET_START', '<div class="usa-accordion-bordered"><ul class="usa-unstyled-list">');
define('USWDS_FIELDSET_END', '</ul></div><!-- USWDS fieldset end -->');
