<?php
/**
 * @file
 * Definition of constants for USWDS theme.
 */

define('USWDS_MENU_REGION_PRIMARY', 'uswds_menu_primary');
define('USWDS_MENU_REGION_SECONDARY', 'uswds_menu_secondary');
define('USWDS_MENU_REGION_SIDE', 'uswds_menu_side');
define('USWDS_MENU_REGION_FOOTER', 'uswds_menu_footer');
define('USWDS_MENU_PATTERN_OPTION', 'uswds-menu-pattern');
define('USWDS_HEADER_STYLE_BASIC', 'basic');
define('USWDS_HEADER_STYLE_EXTENDED', 'extended');
define('USWDS_FOOTER_STYLE_BIG', 'big');
define('USWDS_FOOTER_STYLE_MEDIUM', 'medium');
define('USWDS_FOOTER_STYLE_SLIM', 'slim');
